# RiOS/GNUmakefile
# Copyright (C) 2018 Frank Curie (邱日)
# Here are some OBJ files from all moudules

#####    console moudule    ###################################
console_objs :=$(patsubst src/console/%.cc,\
	build/arch/$(arch)/console/%.o, $(wildcard src/console/*.cc))

build/arch/$(arch)/console/%.o: src/console/%.cc 
	mkdir -p $(shell dirname $@)
	$(CC) $(CFLAGS)  $< -o $@

####     mm moudule   #########################################

mm_objs :=$(patsubst src/mm/%.cc,\
	build/arch/$(arch)/mm/%.o, $(wildcard src/mm/*.cc))

build/arch/$(arch)/mm/%.o: src/mm/%.cc 
	mkdir -p $(shell dirname $@)
	$(CC) $(CFLAGS)  $< -o $@

####     kernel moudule   ######################################

kernel_objs :=$(patsubst src/kernel/%.cc,\
	build/arch/$(arch)/kernel/%.o, $(wildcard src/kernel/*.cc))

build/arch/$(arch)/kernel/%.o: src/kernel/%.cc 
	mkdir -p $(shell dirname $@)
	$(CC) $(CFLAGS)  $< -o $@

####    blk_dev moudule   ######################################
blk_dev_objs :=$(patsubst src/blk_dev/%.cc,\
	build/arch/$(arch)/blk_dev/%.o, $(wildcard src/blk_dev/*.cc))

build/arch/$(arch)/blk_dev/%.o: src/blk_dev/%.cc 
	mkdir -p $(shell dirname $@)
	$(CC) $(CFLAGS)  $< -o $@

####    fs moudule   ######################################
fs_objs :=$(patsubst src/fs/%.cc,\
	build/arch/$(arch)/fs/%.o, $(wildcard src/fs/*.cc))

build/arch/$(arch)/fs/%.o: src/fs/%.cc 
	mkdir -p $(shell dirname $@)
	$(CC) $(CFLAGS)  $< -o $@

####    task moudule   ######################################
task_objs :=$(patsubst src/task/%.cc,\
	build/arch/$(arch)/task/%.o, $(wildcard src/task/*.cc))

build/arch/$(arch)/task/%.o: src/task/%.cc 
	mkdir -p $(shell dirname $@)
	$(CC) $(CFLAGS)  $< -o $@	