# RiOS/GNUmakefile
# Copyright (C) 2018 Frank Curie (邱日)
# Here are some OBJ files from all moudules

#####    console moudule    ###################################
console_objs :=$(patsubst src/console/%.cc,\
	build/arch/$(arch)/console/%.o, $(wildcard src/console/*.cc))

build/arch/$(arch)/console/%.o: src/console/%.cc 
	mkdir -p $(shell dirname $@)
	$(CC) $(CFLAGS)  $< -o $@

####     mm moudule   #########################################

mm_objs :=$(patsubst src/mm/%.cc,\
	build/arch/$(arch)/mm/%.o, $(wildcard src/mm/*.cc))

build/arch/$(arch)/mm/%.o: src/mm/%.cc 
	mkdir -p $(shell dirname $@)
	$(CC) $(CFLAGS)  $< -o $@

####     kernel moudule   ######################################

kernel_objs :=$(patsubst src/kernel/%.cc,\
	build/arch/$(arch)/kernel/%.o, $(wildcard src/kernel/*.cc))

build/arch/$(arch)/kernel/%.o: src/kernel/%.cc 
	mkdir -p $(shell dirname $@)
	$(CC) $(CFLAGS)  $< -o $@
